name: CI

on:
  push:
  pull_request:

jobs:
  node-build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      - run: npm ci
      - run: npm run build

  node-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      - run: npm ci
      - run: npm run test:ci

  node-typecheck:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      - run: npm ci
      - run: npm run typecheck

  node-e2e:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      - run: npm ci
      - run: npm run build

      - name: Bring up Grafana
        run: docker-compose up -d

      - run: npm run e2e

  eslint:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      checks: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      - name: Install dependencies
        run: npm ci

      - name: Save Code Linting Report JSON
        run: npm run lint:report

      - name: Annotate Code Linting Results
        if: always()
        uses: ataylorme/eslint-annotate-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          report-json: "eslint_report.json"

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: eslint-report
          if-no-files-found: error
          retention-days: 30
          path: eslint_report.json
